# Input/output configuration
input_dir: /scratch/data/exatrkx/train_1
output_dir: IN_LP_5
n_files: 100

# Graph building configuration
selection:
    pt_min: 5 # GeV
    phi_slope_max: 0.000262 # 0.0006
    z0_max: 15000 # 100
    n_phi_sections: 1
    n_eta_sections: 1
    eta_range: [-5, 5]
    endcaps: true
    phi_reflect: false
    remove_intersecting_edges: true