model_outdir: trained_models
plot_outdir: plots
verbose: 0
n_epoch: 1
batch_size: 10
prep: 'LP'
pt_cut: '5'
save_every_n_epoch: 1
save_last_n_epoch: 1
phi_reflect: false
tag: 'wide_noPhi'
graph_dir: "IN_LP_5/"